#!/usr/bin/env bash
# GEN-only companion of runCMSDrivers_mc2024_BBbar.sh: bbbar MC with the Pythia8 event
# generation switched on stage by stage. Same fragment, conditions, era, geometry, beamspot
# and com energy as step 1 of that script; every config is generated by cmsDriver.py.
#   ME             hard matrix element only (ISR, FSR, MPI and hadronisation off)
#   ME_PS          + initial- and final-state parton showers
#   ME_PS_MPI      + multiparton interactions
#   ME_PS_MPI_Had  + hadronisation (hadron decays off)
#   ME_PS_MPI_Had_Decay  + hadron decays (the full event, as in the main script)
# PhaseSpace:pTHatMin is set explicitly (PTHATMIN, default 100 GeV) and overrides the fragment.
# For each stage it writes, in the output directory (default GEN/ below the current directory):
#   step1_GEN_<stage>_cfg.py, step1_GEN_<stage>_cfg.driver.log      cmsDriver config and log
#   step1_GEN_<stage>_out.root, step1_GEN_<stage>_out.log           cmsRun output and log
#   genPartAnalyzer_<stage>_out.pdf, .root, .log                     eta-phi maps (GenPartAnalyzer)
# The PDF has one page per generator-record stage that exists in the sample (ME: 1 page,
# ME_PS: 2, ME_PS_MPI: 3, ME_PS_MPI_Had: 4, ME_PS_MPI_Had_Decay: 5), per analysed event.
# Run from an initialized CMSSW environment.
#   EVENTS=1000                            events per stage (default 1000)
#   STAGES="ME ME_PS"                      subset of stages (default all five)
#   PTHATMIN=100                           PhaseSpace:pTHatMin in GeV (default 100)
#   OUTDIR=GEN                             output directory (default GEN)
#   RUN=0                                  only generate the configs, do not run cmsRun
#   ANALYZE=0                              skip the GenPartAnalyzer step
#   ANALYZE_EVENTS=1                       events drawn by GenPartAnalyzer per stage (default 1)
#   DUMP, DUMP_MAX, DUMP_SUB, DUMP_G4_THRESHOLD  as in runCMSDrivers_mc2024_BBbar.sh
set -euo pipefail

events=${EVENTS:-1000}
stages=${STAGES:-"ME ME_PS ME_PS_MPI ME_PS_MPI_Had ME_PS_MPI_Had_Decay"}
pthat_min=${PTHATMIN:-100}
outdir=${OUTDIR:-GEN}
run=${RUN:-1}
analyze=${ANALYZE:-1}
analyze_events=${ANALYZE_EVENTS:-1}
conditions=auto:phase1_2024_realistic
era=Run3_2024
geometry=DB:Extended
beamspot=DBrealistic
com_energy=13600.0
dump=${DUMP:-0}
dump_max=${DUMP_MAX:--1}
dump_sub=${DUMP_SUB:--1}
dump_g4_threshold=${DUMP_G4_THRESHOLD:-1.0}
dump_customise="from JitJetSW.Journey.jitJet_cff import customiseJitJet; process = customiseJitJet(process, level=${dump}, maxElements=${dump_max}, maxSub=${dump_sub}, g4Threshold=${dump_g4_threshold})"

if [[ ${CMSSW_VERSION:-} != CMSSW_15_0_5 ]]; then
  echo "Initialize CMSSW_15_0_5 with 'eval \"\$(scram runtime -sh)\"' first." >&2
  exit 1
fi

journey=$CMSSW_BASE/src/JitJetSW/Journey
analyzer_cfg=$journey/test/genPartAnalyzer_cfg.py

# Pythia8 switches per stage (ISR FSR MPI Had Decay) and the last GenPartAnalyzer stage present
# in the record (1 hard process, 2 parton shower, 3 MPI, 4 hadronisation, 5 hadron decays)
stage_switches() {
  case $1 in
    ME)                  echo off off off off off 1 ;;
    ME_PS)               echo on  on  off off off 2 ;;
    ME_PS_MPI)           echo on  on  on  off off 3 ;;
    ME_PS_MPI_Had)       echo on  on  on  on  off 4 ;;
    ME_PS_MPI_Had_Decay) echo on  on  on  on  on  5 ;;
    *) echo "Unknown stage '$1' (use ME, ME_PS, ME_PS_MPI, ME_PS_MPI_Had, ME_PS_MPI_Had_Decay)" >&2; exit 1 ;;
  esac
}

run_stage() {
  local stage=$1 isr fsr mpi had decay max_stage
  read -r isr fsr mpi had decay max_stage < <(stage_switches "$stage")
  local config="step1_GEN_${stage}_cfg.py"
  local output="step1_GEN_${stage}_out.root"
  local log="step1_GEN_${stage}_out.log"
  local args=("$gen_fragment" --conditions "$conditions" --era "$era" --geometry "$geometry"
              -n "$events" -s GEN --datatier GEN --eventcontent FEVTDEBUG --beamspot "$beamspot"
              --fileout "file:$output" --python_filename "$config" --no_exec)
  local -a customise=(
    "process.generator.comEnergy = cms.double($com_energy)"
    "process.generator.PythiaParameters.processParameters.extend(['PhaseSpace:pTHatMin = $pthat_min', 'PartonLevel:ISR = $isr', 'PartonLevel:FSR = $fsr', 'PartonLevel:MPI = $mpi', 'HadronLevel:all = $had', 'HadronLevel:Hadronize = $had', 'HadronLevel:Decay = $decay'])"
  )
  if (( dump > 0 )); then
    customise+=("$dump_customise")
  fi
  # cmsDriver splits --customise_commands on a literal backslash-n
  local joined=${customise[0]} c
  for c in "${customise[@]:1}"; do joined+='\n'"$c"; done
  args+=(--customise_commands "$joined")

  echo "Stage $stage: ISR=$isr FSR=$fsr MPI=$mpi Had=$had Decay=$decay (pTHatMin=$pthat_min)"
  cmsDriver.py "${args[@]}" > "${config%.py}.driver.log" 2>&1 || {
    cat "${config%.py}.driver.log" >&2; exit 1;
  }
  echo "  Generated $config"
  (( run )) || return 0
  cmsRun "$config" > "$log" 2>&1 || { tail -80 "$log" >&2; exit 1; }
  [[ -s $output ]] || { echo "No output produced: $output" >&2; exit 1; }
  echo "  Completed $output"
  (( analyze )) || return 0

  local aprefix="genPartAnalyzer_${stage}_out"
  local label="sample $stage|ISR $isr, FSR $fsr, MPI $mpi|Had $had, Decay $decay|pTHatMin $pthat_min GeV"   # '|' = new line
  cmsRun "$analyzer_cfg" inputFiles="file:$output" outputFile="$aprefix.root" maxEvents="$analyze_events" \
    maxStage="$max_stage" pdfFile="$aprefix.pdf" sampleLabel="$label" > "$aprefix.log" 2>&1 ||
    { tail -40 "$aprefix.log" >&2; exit 1; }
  [[ -s $aprefix.pdf ]] || { echo "No PDF produced: $aprefix.pdf" >&2; exit 1; }
  echo "  Completed $aprefix.pdf ($max_stage page(s) per event)"
}

# JitJetSW/Journey plugins: GenPartAnalyzer (ANALYZE=1) and the dump customisation (DUMP>0).
# Rebuild when the plugin library is missing or older than the sources.
if (( analyze || dump > 0 )); then
  [[ -d $journey ]] || { echo "Missing package JitJetSW/Journey" >&2; exit 1; }
  plugin_lib=$CMSSW_BASE/lib/$SCRAM_ARCH/pluginJitJetSWJourneyAuto.so
  if [[ ! -s $plugin_lib ]] || [[ -n $(find "$journey/plugins" -name '*.cc' -newer "$plugin_lib") ]] ||
     { (( dump > 0 )) && ! python3 -c 'import JitJetSW.Journey.jitJet_cff' 2>/dev/null; }; then
    echo "Building JitJetSW/Journey"
    # full build (not only the package) so that the edm plugin cache is refreshed
    (cd "$CMSSW_BASE/src" && scram b -j 4 > jitjet_build.log 2>&1) || { cat "$CMSSW_BASE/src/jitjet_build.log" >&2; exit 1; }
  fi
fi

# The fragment lives in this package; cmsDriver resolves it as the python module
# Configuration.GenProduction.<name>, so it is symlinked into the standard location
# (see runCMSDrivers_mc2024_BBbar.sh).
gen_fragment=Configuration/GenProduction/python/BBbar_14TeV_TuneCP5_cfi.py
gen_fragment_src=$CMSSW_BASE/src/JitJetSW/$gen_fragment
[[ -s $gen_fragment_src ]] || { echo "Missing GEN fragment: $gen_fragment_src" >&2; exit 1; }
if [[ ! -e $CMSSW_BASE/src/$gen_fragment ]]; then
  mkdir -p "$CMSSW_BASE/src/${gen_fragment%/*}"
  ln -s "$gen_fragment_src" "$CMSSW_BASE/src/$gen_fragment"
fi
python3 -c 'import Configuration.GenProduction.BBbar_14TeV_TuneCP5_cfi' 2>/dev/null ||
  (cd "$CMSSW_BASE/src/Configuration/GenProduction" && scram b python > /dev/null)

mkdir -p "$outdir"
cd "$outdir"
echo "Writing to $PWD"
for stage in $stages; do
  run_stage "$stage"
done
